/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export type RangeStruct = {
  lowerTick: BigNumberish;
  upperTick: BigNumberish;
  feeTier: BigNumberish;
};

export type RangeStructOutput = [number, number, number] & {
  lowerTick: number;
  upperTick: number;
  feeTier: number;
};

export interface PoolInterface extends utils.Interface {
  functions: {
    "validateTickSpacing(address,(int24,int24,uint24))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "validateTickSpacing"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "validateTickSpacing",
    values: [string, RangeStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "validateTickSpacing",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Pool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    validateTickSpacing(
      pool_: string,
      range_: RangeStruct,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  validateTickSpacing(
    pool_: string,
    range_: RangeStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    validateTickSpacing(
      pool_: string,
      range_: RangeStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    validateTickSpacing(
      pool_: string,
      range_: RangeStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    validateTickSpacing(
      pool_: string,
      range_: RangeStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
