"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OptimalSwap__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var OptimalSwap__factory_1 = require("./OptimalSwap__factory");
Object.defineProperty(exports, "OptimalSwap__factory", { enumerable: true, get: function () { return OptimalSwap__factory_1.OptimalSwap__factory; } });
