/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  OptimalSwap,
  OptimalSwapInterface,
} from "../../../../src/libraries/uniswap/OptimalSwap";

const _abi = [
  {
    inputs: [],
    name: "Invalid_Pool",
    type: "error",
  },
  {
    inputs: [],
    name: "Invalid_Tick_Range",
    type: "error",
  },
  {
    inputs: [],
    name: "Math_Overflow",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212201e1961f75cbf1ec90a8c8ccb904421a1cebf735614e9f03ac79796bd5627d93f64736f6c63430008120033";

type OptimalSwapConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OptimalSwapConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OptimalSwap__factory extends ContractFactory {
  constructor(...args: OptimalSwapConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<OptimalSwap> {
    return super.deploy(overrides || {}) as Promise<OptimalSwap>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): OptimalSwap {
    return super.attach(address) as OptimalSwap;
  }
  override connect(signer: Signer): OptimalSwap__factory {
    return super.connect(signer) as OptimalSwap__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OptimalSwapInterface {
    return new utils.Interface(_abi) as OptimalSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OptimalSwap {
    return new Contract(address, _abi, signerOrProvider) as OptimalSwap;
  }
}
