/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export declare namespace ISlipStreamNonfungiblePositionManager {
  export type MintParamsStruct = {
    token0: string;
    token1: string;
    tickSpacing: BigNumberish;
    tickLower: BigNumberish;
    tickUpper: BigNumberish;
    amount0Desired: BigNumberish;
    amount1Desired: BigNumberish;
    amount0Min: BigNumberish;
    amount1Min: BigNumberish;
    recipient: string;
    deadline: BigNumberish;
    sqrtPriceX96: BigNumberish;
  };

  export type MintParamsStructOutput = [
    string,
    string,
    number,
    number,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber
  ] & {
    token0: string;
    token1: string;
    tickSpacing: number;
    tickLower: number;
    tickUpper: number;
    amount0Desired: BigNumber;
    amount1Desired: BigNumber;
    amount0Min: BigNumber;
    amount1Min: BigNumber;
    recipient: string;
    deadline: BigNumber;
    sqrtPriceX96: BigNumber;
  };
}

export declare namespace IAutomanCommon {
  export type ZapOutParamsStruct = {
    token0FeeAmount: BigNumberish;
    token1FeeAmount: BigNumberish;
    tokenOut: string;
    tokenOutMin: BigNumberish;
    swapData0: BytesLike;
    swapData1: BytesLike;
    isUnwrapNative: boolean;
  };

  export type ZapOutParamsStructOutput = [
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    boolean
  ] & {
    token0FeeAmount: BigNumber;
    token1FeeAmount: BigNumber;
    tokenOut: string;
    tokenOutMin: BigNumber;
    swapData0: string;
    swapData1: string;
    isUnwrapNative: boolean;
  };

  export type PermitStruct = {
    deadline: BigNumberish;
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
  };

  export type PermitStructOutput = [BigNumber, number, string, string] & {
    deadline: BigNumber;
    v: number;
    r: string;
    s: string;
  };
}

export interface IAutomanSlipStreamMintRebalanceInterface
  extends utils.Interface {
  functions: {
    "mintFromTokenIn((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),address,uint256,bytes,bytes)": FunctionFragment;
    "mintOptimal((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),bytes,uint256,uint256)": FunctionFragment;
    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))": FunctionFragment;
    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "mintFromTokenIn"
      | "mintOptimal"
      | "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))"
      | "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "mintFromTokenIn",
    values: [
      ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      string,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintOptimal",
    values: [
      ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))",
    values: [
      ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      BigNumberish,
      BytesLike,
      boolean,
      IAutomanCommon.ZapOutParamsStruct,
      IAutomanCommon.PermitStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))",
    values: [
      ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      BigNumberish,
      BytesLike,
      boolean,
      IAutomanCommon.ZapOutParamsStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintFromTokenIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintOptimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAutomanSlipStreamMintRebalance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAutomanSlipStreamMintRebalanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    mintFromTokenIn(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenIn: string,
      tokenInFeeAmount: BigNumberish,
      swapData0: BytesLike,
      swapData1: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    mintOptimal(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      swapData: BytesLike,
      token0FeeAmount: BigNumberish,
      token1FeeAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      permit: IAutomanCommon.PermitStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  mintFromTokenIn(
    params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
    tokenIn: string,
    tokenInFeeAmount: BigNumberish,
    swapData0: BytesLike,
    swapData1: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  mintOptimal(
    params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
    swapData: BytesLike,
    token0FeeAmount: BigNumberish,
    token1FeeAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))"(
    params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
    tokenId: BigNumberish,
    swapData: BytesLike,
    isCollect: boolean,
    zapOutParams: IAutomanCommon.ZapOutParamsStruct,
    permit: IAutomanCommon.PermitStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))"(
    params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
    tokenId: BigNumberish,
    swapData: BytesLike,
    isCollect: boolean,
    zapOutParams: IAutomanCommon.ZapOutParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    mintFromTokenIn(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenIn: string,
      tokenInFeeAmount: BigNumberish,
      swapData0: BytesLike,
      swapData1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        tokenId: BigNumber;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
      }
    >;

    mintOptimal(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      swapData: BytesLike,
      token0FeeAmount: BigNumberish,
      token1FeeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        tokenId: BigNumber;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
      }
    >;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      permit: IAutomanCommon.PermitStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        newTokenId: BigNumber;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
      }
    >;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        newTokenId: BigNumber;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    mintFromTokenIn(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenIn: string,
      tokenInFeeAmount: BigNumberish,
      swapData0: BytesLike,
      swapData1: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    mintOptimal(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      swapData: BytesLike,
      token0FeeAmount: BigNumberish,
      token1FeeAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      permit: IAutomanCommon.PermitStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintFromTokenIn(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenIn: string,
      tokenInFeeAmount: BigNumberish,
      swapData0: BytesLike,
      swapData1: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    mintOptimal(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      swapData: BytesLike,
      token0FeeAmount: BigNumberish,
      token1FeeAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool),(uint256,uint8,bytes32,bytes32))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      permit: IAutomanCommon.PermitStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "rebalance((address,address,int24,int24,int24,uint256,uint256,uint256,uint256,address,uint256,uint160),uint256,bytes,bool,(uint256,uint256,address,uint256,bytes,bytes,bool))"(
      params: ISlipStreamNonfungiblePositionManager.MintParamsStruct,
      tokenId: BigNumberish,
      swapData: BytesLike,
      isCollect: boolean,
      zapOutParams: IAutomanCommon.ZapOutParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
